# Universalidade da docência como profissão

O mundo do trabalho sempre esteve presente na minha vida. Seja por conta das atividades profissionais que meus pais exerciam ou seja pela minha vontade, a partir da adolescência, de ser independente. O trabalho se mostrou como parte natural da minha vida muito cedo, mas não por necessidade. A condição financeira da minha família foi determinante no meu **acesso** à educação e, caso fosse meu desejo, poderia deixar para ingressar no mundo do trabalho mais tarde. Entretanto, apesar da minha insegurança em relação às minhas competências, a vontade 

E claro, a docência fez parte desse mundo desde o início. Minha primeira atividade profissional foi como professora de inglês. 

Quando retornei de um intercâmbio nos Estados Unidos aos 16 anos, comecei a lecionar. 

Escolher a profissão é sempre um desafio, especialmente quando somos muito jovens e associamos a perspectiva do trabalho às disciplinas que cursamos ao longo da educação básica. De fato, eu já tinha uma profissão quando precisei preencher o formulário de inscrição para o vestibular com minhas opções de curso universitário. 

Durante muitos anos eu fui apaixonada por biologia, mais especificamente por zoologia, mas não poderia dissecar um animal em laboratório. Entretanto, no ensino médio, fiquei apaixonada por química e física. Cheguei a pensar (nem acredito nisso hoje) em cursar física básica no ensino superior. Entretanto, e também devido à influência das escolhas profissionais da minha mãe, considerei as engenharias como o caminho profissional mais alinhado com minha vocação. Hoje acredito que todos temos vocação para quaisquer áreas de conhecimento. Basta que estejamos motivados. 

Dentre as engenharias, a minha primeira opção seria cursar engenharia química; bem intuitivo. Entretanto, quando ingressei na universidade, em 1997, havia uma recessão econômica que limitava bastante as oportunidades de trabalho para engenheiros. Assim, a minha linha de pensamento foi escolher o curso universitário conforme empregabilidade ou possibilidade de exercer a profissão informalmente. Assim, dentre as diversas opções em engenharia, a engenharia civil pareceu mais versátil para que eu pudesse, eventualmente, ter uma fonte de renda, mesmo que informal. 

E foi assim. Fiz vestibular para engenharia civil e fui aprovada na FUMEC, PUCMinas e UFMG. Felizmente, ao ser aprovada nas três isntituições, pude escolher e comecei, em fevereiro de 1997, o curso de engenharia civil na UFMG. 

Instituto de ciências exatas e laboratórios de topografia foram minha casa durante dois anos, que consolidam o "ciclo básico" das engenharias. Durante esse período eu não consegui explorar a engenharia como profissão. Eram disciplinas nada aplicadas e eu seguia exercendo minha atividade profissional como professora de inglês. Em 1997 consegui uma colocação em uma escola de línguas e, pela primeira vez, tive acesso a um curso de qualificação para exercer o ensino de língua estrangeira. Foi um diferencial naquele momento da minha vida, pois percebi que, apesar de adorar lecionar, havia também muita técnica e processos que potencialmente melhorariam minhas aulas. 

Segui lecionando nessa escola por um ano. Após esse período, optei por ministrar aulas particulares e em grupos e consegui manter essa atividade como minha profissão e fonte de renda até o meio do curso de graduação. No sexto período, resolvi investir na minha formação em engenharia e fazer um estágio em uma construtora, para explorar os caminhos que a engenharia civil possibilitava. Fiz estágio em um setor de orçamento de obras e não consegui cumprir meu contrato de seis meses. Pedi desligamento no quinto mês, pois não conseguia me dedicar a fazer as mesmas atividades diariamente durante o mês.

Como meu dia tem apenas 24 horas (às vezes ainda esqueço disso), precisei reduzir minha carga de aulas de inglês e, no sétimo período, consegui uma vaga como bolsista de iniciação científica. O projeto era intitulado "**Mobilidade** Residencial e Sistema de Transporte na Região Metropolitana de Belo Horizonte" e foi desenvolvido no Departamento de Engenharia de Transportes e Geotecnia sob orientação do professor _David José Ahouagi Vaz de Magalhães_. 

Ao final do curso, não tive dúvidas de que precisaria aprofundar meus conhecimentos após ter escolhido a área de engenharia de transportes para atuação. Na graduação, as disciplinas dessa área de conhecimento são abrangentes e têm como objetivo apresentar os grandes tópicos que compõe a engenharia de transportes. Infelizmente, em Belo Horizonte, não havia a possibilidade de realizar um mestrado nessa área. Assim, pesquisei alguns programas, coletei algumas informações sobre como montar um pre-projeto de pesquisa e fiz a inscrição nos programas da USP-São Carlos, da UFRJ e do IME. A inscrição na UFRJ e no IME foi presencial e, naquele momento, me decidi pelo IME. Não por conta essencialmente da qualidade do curso, mas devido à **localização** do IME em relação ao Campus da UFRJ na ilha do função. A **localização** já se manifestava como instrumento de **decisão** na minha vida. 

Fui aprovada nos três programas e decidi ir para o Rio de Janeiro, me matriculando no IME. O principal fator para escolha do Rio e não de São Carlos estava relacionado ao coração, e a **distância** entre Belo Horizonte e as respectivas cidades foi decisiva. 

Cresci acreditando que as pessoas conseguem conquistas bens materiais e status por meio de esforço e mérito individual. Acreditava que a possibilidade de gerar valor para as empresas era o que diferenciava um bom engenheiro de um mau profissional. Assim, evitando olhar para o público, direcionei o meu projeto de mestrado para o transporte de cargas, entendendo, naquele momento, que estaria isenta de decisões públicas interferindo no meu projeto acadêmico e na minha atividade profissional. 

Assuntos do coração têm um capítulo especial neste memorial, pois tiveram um papel importante na maior parte das escolhas profissionais e acadêmicas que fiz. 

2003 foi um ano meio de mudanças. Mudanças de emprego, de casa e de objetivos. Após cumprir os créditos básicos no IME, resolvi trancar o curso e voltar para Belo Horizonte. Como não consegui ficar sem trabalhar, busquei estágio na empresa-referência em consultoria de transportes em BH naquela época: o grupo Tectran. Bati à porta do escritório da Tectran, com meu singelo currículo embaixo do braço e perguntei se tinham alguma vaga para mim. Acharam estranho essa abordagem, mas coloquei-me à disposição inclusive para estagiar como mestranda na empresa e me fizeram a proposta de trabalhar como estagiária recebendo remuneração equivalente àquela da bolsa de mestrado da época. Foi maravilhoso. A equipe era acolhedora e, como o grupo ainda era pequeno, tive a oportunidade de colaborar com projetos em diferentes áreas e de, efetivamente, aprender a trabalhar. Penso que essa tenha sido a minha primeira experiência profissional como engenheira e adorei! Adorei não fazer a mesma coisa todos os dias, adorei eventualmente estudar para propor algum caminho metodológico para os projetos e de efetivamente concluir etapas ao longo da vida profissional. 

Eu nunca me senti confortável em não experimentar a concepcão, o desenvolvimento e o fechamento das minhas atividades. Não ver o resultado da minha contribuição, seja como professora ou como engenheira, me desmotivava e não 



E que a minha aventura como professora de inglês aos 16 anos foi bastante audaciosa e exitosa. Comecei a lecionar para uma amiga e uma tia que encararam a experiência. Sofia falou que o êxito como professora era, possivelmente, resultado da inexperiência e da vontade de fazer diferente. Sem preconceitos e sem expectativas, construí intuitivamente  

Ao longo da elaboração deste memorial, comentei com minha filha Sofia (na seção de assuntos do coração vocês conhecerão como ela veio fazer parte da minha essência) que eu sempre me motivei mais com atividades que apresentavam início, meio e fim. 


Em 2003, em meio às atividades de consultoria, consegui uma colocação, aos 24 anos, para atuar como professora na Faculdade Novos Horizonte. Apostaram em mim, mesmo

Lecionei Logística 



Entrei na vale em setembro de 2003 e etapa mais difícil do processo seletivo foi pedir demissão da minha posição de estagiária na Tectran. Tinha aprendido tanto e nutria afeto pelas pessoas e pelo acolhimento recebido. Mas a vida segue e me desligar daquela posição não era fechar portas e sim buscar novas experiências. Quando ao processo seletivo, foram inúmeras etapas e, mais uma vez, contei com minha formação ao longo da vida e entrei no processo de maneira despretenciosa, por indicação do amigo _Maurício Aguiar_. 

Foi curioso que, durante o processo seletivo, passei por dois gerentes gerais na entrevista final. O primeiro a me entrevistar identificou minha inaptidão a rotinas e, portanto, a trabalhar na operação. O que não é rotina na operação ferroviária, é problema! O primeiro gerente a me entrevistar me encaminhou para o segundo e o resultado foi que fui a única "Engenheira Ferroviária" que não estava lotada na Diretoria de Operações. Fui alocada em uma área de estudos operacionais sob a Diretoria de Planejamento. Essa decisão dos gestores foi muito assertiva e alinhada com o meu potencial de contribuição para a empresa.  

Assumimos na Vale, eu e meus colegas e amigos Engenheiros Ferroviários, no dia 15 de setembro de 2003. Entramos na primeira edição do programa de trainee "Engenheiro Ferroviário", cujo objetivo era capacitar jovens talentos para atuar no mercado ferroviário. Por anos não houve investimento em mão de obra para operação e gestão de ferrovias. Assim, fez necessário que as operadoras investissem em qualificação, como ainda é realidade nesse setor. 

Foram três meses de aulas e muita aprendizagem. Também, de viagens, companheirismo e construção de novas amizades. Essa capacitação aconteceu em imersão no saudoso Othon Palace Hotel de Belo Horizonte e posteriormente viajamos visitando as diferentes instalações ferroviárias da Vale nas ferrovias Estrada de Ferro Vitória a Minas, Estrada de Ferro Carajás e Ferrovia Centro Atlântica. Felizmente, durante o treinamento, fiquei em casa (assuntos do coração são fortes!) e frequentei as aulas diárias. 

Aprendemos muito e ao final, fui alocada para desenvolver projetos internos de melhoria, trabalhando com simulação de trens.... 

Eu respirava engenharia econômica e até restaurantes foram apelido pela equipe como VPL, por apresentarem um ótimo custo-benefício. Aprendi que a qualidade do meu trabalho é diretamente proporcional ao tempo que tenho para fazê-lo. Tive que aprender a controlar a vontade de fazer melhor, pois os prazos não eram flexíveis e a entrega tinha que acontecer. Aprendi também que uma empresa como a Vale, apesar de permeada de processos decisórios exclusivamente fundamentados em uma disputa de poder de mercado e política, era orientada à remuneração de capital. Que princípios éticos, que a qualidade técnica da engenharia e até mesmo as situações de risco podem ser descartados se remunerarmos o acionista. Eu precisava transformar o resultado de estudos de melhoria operacional em resultado financeiro. "Dá VPL?" Era a pergunta do diretor na decisão de investimento.  

Alguns meses depois, houve, durante uma das muitas reestruturações gerenciais, a demanda de ume profissional na área de planejamento ferroviário no longo e médio prazos. Essa área era a interface entre as funções comerciais e operacionais da ferrovia e trabalhávamos organizando os fluxos a serem realizados nos horizontes mensal e anual. Foi maravilhoso entender um pouco mais sobre o sistema ferroviário como serviço e me tornar uma das pessoas responsáveis pelo dimensionamento de vagões, locomotivas e o arranjo dos trens com todas as restrições que a ferrovia . Mas o encatamento  

Fui responsável pela coordenação de dados obtidos a partir de diferentes ERPs (Enterprise Resource Planning) que eram os sistemas de gestão diferentes para cada ferrovia. Recebia ainda dados das áreas de manutenção de material rodante e via permanente. Consolidando e coordenando as informações, gerávamos um instrumento denominado Book PPC (planejamento, programação e controle) que era um conjunto de planilhas com indicadores de desempenho ferroviários. Aquele documento era encaminhado para toda a Diretoria de Logística visando acompanhamento de metas e resultados, nas diferentes dimensões que eram possíveis

Hoje faço dessa experiência a base para construção do conhecimento em ciência de dados e para que eu consiga apresentar esse conteúdo de forma aplicada para os alunos. 

Durante meu período na Vale, de setembro de 2003 a maio de 2005, não consegui coordenar minhas atividades como docente e, portanto, solicitei suspensão do meu contrato na Faculdade Novos Horizontes e fiquei até 2005 vinculada à instituição, mas sem lecionar. Mais uma vez sou grata pela confiança e pela oportunidade de obter experiência na docência no ensino superior. 

Em 2005, após pedir desligamento da Vale, lecionei em faculdades particulares em cursos de administração e como professora substituta de volta ao Departamento de Engenharia de Transportes e Geotecnia da UFMG. As faculdades particulares - FUNCESI - Fundação Uni.... e Novos Horizonte foram oportunidades únicas pois conseguir colocações profissionais sem experiência praticamente inviabiliza a construção de experiências. É o ciclo perverso do início da carreira de qualquer jovem. Nessas universidade lecionei disciplinas relacionadas à gestão das operações e à aplicação de métodos quantitativos, como administração da produção, da qualidade e logística. Essas disciplinas estavam relacionadas com minha formação básica na engenharia civil e minha especialização no mestrado. 

Quando fui professora substituta na UFMG, enfrentei um desafio profissional que tinha um peso emocional importante. O professor _Baeta_ precisou se aposentar por idade e eu assumiria seu lugar. Ele, como sempre, foi muito solícito ao fazer um processo suave de transição das disciplinas. Entretanto, eu me sentia mal por assumir seu lugar, sendo que ele ainda gostaria de exercer a docência. Ainda, discordava de algumas práticas em sala de aula adotadas por ele quando estudante e queria fazer diferente. 








Escolha pela docência
Lecionar no contexto dos centros educacionais privados, hoje em protagonismo no cenário atual. 
Casamento
Concurso para o CEFET

